apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: xdmod
  name: xdmod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xdmod
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8hpc-compute: "true"
        io.kompose.service: xdmod
    spec:
      containers:
        - args:
            - serve
          image: ubccr/hpcts:xdmod-2022.07
          name: xdmod
          ports:
            - containerPort: 443
              hostIP: 127.0.0.1
            - containerPort: 22
          resources: {}
      hostname: xdmod
      restartPolicy: Always
status: {}
