apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: ldapsvc
  name: ldapsvc
spec:
  type: ClusterIP
  ports:
    - name: "636"
      port: 636
      targetPort: 636
    - name: "389"
      port: 389
      targetPort: 389
  selector:
    io.kompose.service: ldapsvc
status:
  loadBalancer: {}
