apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: ondemand
  name: ondemand
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ondemand
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8hpc-compute: "true"
        io.kompose.service: ondemand
    spec:
      containers:
        - args:
            - serve
          image: ubccr/hpcts:ondemand-2022.07
          name: ondemand
          ports:
            - containerPort: 3443
              hostIP: 127.0.0.1
            - containerPort: 5554
              hostIP: 127.0.0.1
            - containerPort: 22
          resources: {}
      hostname: ondemand
      restartPolicy: Always
status: {}
