apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8hpc-compute: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          image: mariadb:10.11.2
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: docker-initdb
            - mountPath: /etc/mysql/conf.d
              name: mysql-conf
            - mountPath: /etc/slurm/slurmdbd.conf
              name: slurmdbd-conf
            - mountPath: /var/lib/mysql
              name: var-lib-mysql
      hostname: mysql
      restartPolicy: Always
      volumes:
        - name: docker-initdb
        hostPath:
          path: /opt/keys/k8hpc/database
        - name: mysql-conf
        hostPath:
          path: /opt/keys/k8hpc/database
        - name: slurmdbd-conf
          path: /opt/keys/k8hpc/slurm/slurmdbd.conf
status: {}
