apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mysql2"
  storageClassName: local

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-claim2
  name: mysql-claim2
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
