apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-lib-mysql
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/var-lib-mysql"
  storageClassName: local
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: var-lib-mysql
  name: var-lib-mysql
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
