apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mongodb"
  storageClassName: local

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-claim0
  name: mongodb-claim0
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
