apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: cpn03
  name: cpn03
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cpn03
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8hpc-compute: "true"
        io.kompose.service: cpn03
    spec:
      containers:
        - args:
            - slurmd
          image: ubccr/hpcts:slurm-2022.07
          name: cpn03
          ports:
            - containerPort: 22
            - containerPort: 6818
          volumeMounts:
            - name: home
              mountPath: /opt/home
          resources: {}
      hostname: cpn03
      volumes:
        - name: home
          hostPath:
            path: /opt/home
      restartPolicy: Always
status: {}
