apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mongodb"
  storageClassName: local

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadb
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/data-db"
  storageClassName: local

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql0
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mysql0"
  storageClassName: local
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mysql1"
  storageClassName: local
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
spec:
  capacity:
   storage: 200Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/mysql2"
  storageClassName: local
