apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmctld
  name: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmctld
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8hpc-compute: "true"
        io.kompose.service: slurmctld
    spec:
      containers:
        - args:
            - slurmctld
          image: ubccr/hpcts:slurm-2022.07
          name: slurmctld
          ports:
            - containerPort: 22
            - containerPort: 6817
          resources: {}
      hostname: slurmctld
      restartPolicy: Always
status: {}
