apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-munge
spec:
  capacity:
   storage: 100Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/etc-munge"
  storageClassName: local
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: etc-munge
  name: etc-munge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
