apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurmdbd-state
spec:
  capacity:
   storage: 100Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/users/lngo/vc/slurmdbd-state"
  storageClassName: local
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: slurmdbd-state
  name: slurmdbd-state
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
